// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameWalletInfo = "wallet_info"

// WalletInfo mapped from table <wallet_info>
type WalletInfo struct {
	ID         int64  `gorm:"column:id;primaryKey" json:"id,string"`
	Category   int32  `gorm:"column:category;not null" json:"category"`      // 钱包类型，0，一般用途，；1，充值账单
	Name       string `gorm:"column:name;not null" json:"name"`              // 钱包名称，可以是账户pubKey
	Path       string `gorm:"column:path;not null" json:"path"`              // 钱包HdPath
	Address    string `gorm:"column:address;not null" json:"address"`        // 钱包地址
	Deleted    int32  `gorm:"column:deleted;not null" json:"deleted"`        // 删除标志，1，已删除；0， 未删除
	CreateTime int64  `gorm:"column:create_time;not null" json:"createTime"` // 创建时间
	UpdateTime int64  `gorm:"column:update_time;not null" json:"updateTime"` // 更新时间
}

// TableName WalletInfo's table name
func (*WalletInfo) TableName() string {
	return TableNameWalletInfo
}
